; VERIFICO PROBLEMAS DE SEÇÃO NO LUGAR ERRADO, TRANSIÇÃO BURRA E ACESSO À SEÇÕES INEXISTESTES
; VERIFICO SE O PAR BEGIN/END ESTÁ FUNCIONANDO DIREITINHO
; VERIFICO SE SPACE ESTÁ RECEBENDO UM ARGUMENTO ESPERTO OU NÃO


SECTION DATA		; NÃO PODE TER SEÇÃO DATA ANTES DE SEÇÃO TEXT!
SECTION ROTULO		; SOH EXISTEM AS SEÇÕES DATA E SECTION, NADA MAS

SECTION TEXT
SECTION TEXT		; O ROTEIRO NÃO ME DIZ SE EU TENHO QUE PROIBIR... EU VOU IGNORAR ESSA LINHA SE JÁ ESTIVER EM 'TEXT'
SECTION DATA
SECTION DATA		; O ROTEIRO NÃO ME DIZ SE EU TENHO QUE PROIBIR... EU VOU IGNORAR ESSA LINHA SE JÁ ESTIVER EM 'DATA'

SECTION TEXT

	END				; TEM QUE TER UM BEGIN ANTES DE UM END!
	BEGIN
		BEGIN			; NÃO VOU PERMITIR ANINHAMENTO DE 'BEGIN'
		END
		END				; TEM QUE TER UM BEGIN PARA FECHAR
	BEGIN

;VERIFICANDO QUESTÕES DE NUMERO DE ARGUMENTOS
SECTION DATA
	CONST				; NÃO EH VÁLIDO, FALTA ARGUMENTO
	CONST	1			; VÁLIDO
	CONST	-1			; VÁLIDO
	CONST	-			; NÃO EH VÁLIDO
	CONST	2		2	; NÃO EH VÁLIDO, ARGUMENTOS DEMAIS

	SPACE
	SPACE	10
	SPACE	10		10	; NAO EH VÁLIDO, ARGUMENTOS DEMAIS

	PUBLIC									; ARGUMENTOS DE MENOS
	PUBLIC	CACHORRINHO						; CERTINHO
	PUBLIC	GATINHO			PASSARINHO		; ARGUMENTOS DE MAIS

	EXTERN									;EXTERN SEM RÓTULO, NÃO PODE
ROT: EXTERN									; EXTERN COM RÓTULO, PODE
	EXTERN	ROT 							;EXTERN COM ARGUMENTO, NÃO PODE

; VERIFICANDO ERROS DE ARGUMENTO INVÁLIDO/BURRO
SECTION DATA
	CONST	1
	SPACE	0			; BURRICE INOFENSIVA... NÃO SEI SE EU TENHO QUE PROIBIR OU NÃO
	SPACE	-1			; BURRICE PERIGOSA! ISSO EU PROIBO
	SPACE	ALPHA		; NÃO EH VÁLIDO, ARGUMENTO NÃO EH NUMÉRICO

; FALTOU FECHAR O END!
