; VERIFICO PROBLEMAS DE SEÇÃO NO LUGAR ERRADO, TRANSIÇÃO BURRA E ACESSO À SEÇÕES INEXISTESTES
; VERIFICO SE O PAR BEGIN/END ESTÁ FUNCIONANDO DIREITINHO
; VERIFICO SE SPACE ESTÁ RECEBENDO UM ARGUMENTO ESPERTO OU NÃO

SECTION TEXT
SECTION TEXT		; O ROTEIRO NÃO ME DIZ SE EU TENHO QUE PROIBIR... EU VOU IGNORAR ESSA LINHA

SECTION DATA
SECTION DATA		; O ROTEIRO NÃO ME DIZ SE EU TENHO QUE PROIBIR... EU VOU IGNORAR ESSA LINHA

SECTION ROTULO		; SOH EXISTEM AS SEÇÕES DATA E SECTION, NADA MAS

;VERIFICANDO QUESTÕES DE NUMERO DE ARGUMENTOS
SECTION DATA
	CONST				; NÃO EH VÁLIDO, FALTA ARGUMENTO
	CONST	1			; VÁLIDO
	CONST	-			; NÃO EH VÁLIDO
	CONST	-1			; NÃO EH VÁLIDO
	CONST	2		2	; NÃO EH VÁLIDO, ARGUMENTOS DEMAIS

	SPACE
	SPACE	10
	SPACE	10		10	; NAO EH VÁLIDO, ARGUMENTOS DEMAIS

; VERIFICANDO ERROS DE ARGUMENTO INVÁLIDO/BURRO
SECTION DATA
	CONST	1
	SPACE	0			; BURRICE INOFENSIVA... NÃO SEI SE EU TENHO QUE PROIBIR OU NÃO
	SPACE	-1			; BURRICE PERIGOSA! ISSO EU PROIBO
	SPACE	ALPHA		; NÃO EH VÁLIDO, ARGUMENTO NÃO EH NUMÉRICO
