; VOU TESTAR AS INSTRUÇÕES E POSSÍVEIS PROBLEMAS DE QUANTIDADE DE ARGUMENTO
; ASSUMO QUE EU ESOTU DANDO CONTA DE USAR UM ROTULO SEM PROBLEMAS.

SECTION TEXT

        ;CONFIRMANDO SE TODAS AS INSTRUÇÕES VÁLIDAS SÃO RECONHECIDAS
		ADD ROT
		SUB ROT
		MULT ROT
		DIV ROT

EXEC:	JMP		EXEC
		JMPN	EXEC
		JMPP	EXEC
		JMPN	EXEC

		COPY	ROT,	ROT
		LOAD	ROT
		STORE	ROT
		INPUT	ROT
		OUTPUT	ROT
		STOP

		; OBSERVANDO PROBLEMAS DE QUANTIDADE DE ARGUMENTOS
		ADD 				; NAO EH VÁLIDO, ARGUMENTOS DE MENOS
		ADD ROT				; VÁLIDO
		ADD ROT ROT			; NAO EH VÁLIDO, ARGUMENTOS DEMAIS

		STOP				; VÁLIDO
		STOP ROT			; NAO EH VÁLIDO, ARGUMENTOS DEMAIS
		STOP ROT ROT		; NÃO EH VÁLIDO, ARGUMENTOS DEMAIS
		STOP ROT, ROT		; NÃO EH VÁLIDO, ARGUMENTOS DEMAIS

		COPY				; NÃO EH VÁLIDO, ARGUMENTOS DE MENOS
		COPY ROT			; NÃO EH VÁLIDO, ARGUMENTOS DE MENOS
		COPY ROT ROT		; NÃO EH VÁLIDO, FALTA A VÍRGULA
		COPY ROT,			; NÃO EH VÁLIDO, ARGUMENTOS DE MENOS
		COPY ROT, ROT		; VÁLIDO
		COPY ROT ROT ROT	; NÃO EH VÁLIDO, ARGUMENTOS DE MAIS E FALTA A VÍRGULA
		COPY ROT, ROT ROT	; NÃO EH VÁLIDO, ARGUMENTOS DE MAIS
		COPY ROT, ROT, ROT	; NÃO EH VÁLIDO, ARGUMENTOS DE MAIS

SECTION DATA
ROT:	CONST 1
