
SECTION TEXT

; PROBLEMAS DE ':' E MODIFICADORES
	ROTULO		ADD 	ALPHA		; INVÁLIDO, FALTA O ':'
	ROTULO+1:	ADD		ALPHA		; INVÁLIDO, +1 EH INVÁLIDO PARA OPERAR O RÓTULO
	ROTULO+1	ADD		ALPHA		; INVÁLIDO, +1 EH INVÁLIDO PARA OPERAR O RÓTULO, E FALTA O :

; PROBLEMAS DE ROTULOS REDEFINIDOS E NÃO DEFINIDOS
ALPHA:			ADD		ALPHA
ALPHA:			SUB		ALPHA		; INVÁLIDO, RÓTULO REDEFINIDO!
				ADD		BETA		; INVÁLIDO, RÓTULO NÃO DEFINIDO EM LUGAR NENHUM

; POSSÍVEIS PROBLEMAS DE RECEBER INFORMAÇÃO EXTERNA
				ADD		APARTAMENTO

; DIVISÃO POR ZERO
				DIV		ZERO				; INVÁLIDO, NÃO PODEMOS DIVIDIR POR ZERO
				JMP		zero				; INVÁLIDO, NÃO PODEMOS PULAR PARA A SEÇÃO DATA
				store	zero				; INVÁLIDO, NÃO PODEMOS ALTERAR UMA CONSTANTE
				ADD 	alpha+21			; INVÁLIDO, TENTANDO ACESSAR ALGUM LUGAR FORA DA MEMORIA RESERVADA

CASA:			EXTERN
PUBLIC			PONTE

SECTION DATA

APARTAMENTO:	EXTERN
PUBLIC			BARRACO
GOL:	CONST	1
ROT_ALEATORIO:	CONST 30
ZERO:			const 0
